### ISSUE TITLE
Host throws Failed to start up socket despite FF launching

### ISSUE THREAD

**Issue by dhrobbins** [TestStack/TestStack.Seleno#173]
Have some strange behavior.  I ran simple test based on the documentation and on the first run Firefox opened, fired up Google and performed a search.  The testfixture passed, but Firefox threw an error stating that the user profile was not accessible.  Now when I run the test again I get the following exception:

```
TestSeleno.Tests.GoogleTestFixture.CanSearchForGoogle:
System.TypeInitializationException : The type initializer for 'TestSeleno.Host' threw an exception.
  ----> Autofac.Core.DependencyResolutionException : An exception was thrown while executing a resolve operation. See the InnerException for details. ---> Failed to start up socket within 45000 ms. Attempted to connect to the following addresses: 127.0.0.1:7055 (See inner exception for details.)
  ----> OpenQA.Selenium.WebDriverException : Failed to start up socket within 45000 ms. Attempted to connect to the following addresses: 127.0.0.1:7055
```

My pages are:

```
public class GooglePage : Page
    {
        public GooglePage StartSearch(string terms)
        {
            Find.Element(By.Name("q"))
            .SendKeys(terms);

            return this;
        }

        public ResultsPage DoSearch()
        {
            return Navigate.To<ResultsPage>(By.Name("btnG"));
        }
    }
```

And the host looks pretty standard:

```
public static class Host
    {
        public static readonly SelenoHost Instance = new SelenoHost();

        static Host()
        {
            Instance.Run(configure => {
                configure.WithWebServer(new InternetWebServer("http://www.google.co.uk"));
                configure.UsingCamera(@"D:\VS12Dev\TestSeleno\TestSeleno\screenshots");
            });
        }
    }
```

Is there a way to run a headless test ala phantomjs?  Ultimately I would like to run tests without Firefox launching.

**Comment by mahimalokre** [comment]
For me also WebDriverException was unhandled is coming below in detail i have mentioned.
An unhandled exception of type 'OpenQA.Selenium.WebDriverException' occurred in WebDriver.dll

Additional information: Failed to start up socket within 45000 milliseconds. Attempted to connect to the following addresses: 127.0.0.1:7055

I am using Selenium web driver of 2.53(updated) in windows 7
and Firefox version is 47 but i read somewhere that it is not compatible to selenium(2.53) so i have uninstall it and reinstall 46.1 version but now also this same exception is coming.
I tried but not getting can anyone suggest me how to handle this exception.

**Comment by ghost** [comment]
Having the same issue as @Mahimalokre .
Has anyone solved this issue?

**Comment by mwhelan** [comment]
It seems that the old Firefox WebDriver is no longer supported with Firefox 47. You need to use the new Marionette driver instead. Details [here](https://github.com/seleniumhq/selenium/issues/2110);

I have not had a chance to investigate Marionette yet, but from a Seleno perspective it should just be a case of creating a RemoteWebDriver for Marionette, following the setup instructions from the Marionette WebDriver page [here](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette/WebDriver), and passing it to the WithRemoteWebDriver method during Seleno configuration. You can see an example of doing this in our [docs](https://seleno.readme.io/docs/basic-configuration). 

Please let us know if this addresses your issue.
