### ISSUE TITLE
How do you run the sample tests?

### ISSUE THREAD

**Issue by hswander** [TestStack/TestStack.Seleno#207]
We have installed your solution but cannot see anything under test explorer, and can't get any of the  mvc movies and music store tests to run or debug.

All of the nuget packages seem to be installed. I have run these tests before without any problems.

Has something changed? Are we are missing?

This is Visual Studio 2013, update 4.

Thank you.

Holly

**Comment by robdmoore** [comment]
Do you have the Visual Studio extension that runs NUnit tests in Visual Studio test runner?

**Comment by hswander** [comment]
We installed the NUnit Test Adapter extension and now the tests are running. Thank you.
