### ISSUE TITLE
How do you start a seleno host with maximized browser window?

### ISSUE THREAD

**Issue by lchong0412** [TestStack/TestStack.Seleno#212]
It starts with a half sized window, can I start with a maximized window?
Thanks

**Comment by sirj77** [comment]
You just need to add this line into your Host class:
```c#
Instance.Application.Browser.Manage().Window.Maximize();
```

**Comment by robdmoore** [comment]
Thanks @sirj77

**Comment by thnk2wn** [comment]
When I do this it does maximize the browser but that appears to cause subsequent test inputs to fail. Removing the maximize code the test works as expected but non-maximized. Is the below incorrect or maybe a different in Chrome now?

```
public static class Host
{
    public static readonly SelenoHost Instance = new SelenoHost();

    static Host()
    {
        var chromeOptions = new ChromeOptions();            
        Instance.Run("Hakata.Web", 6600, c => c
            .UsingLoggerFactory(new ConsoleFactory())
            .WithRemoteWebDriver(() => BrowserFactory.Chrome(chromeOptions))
            .UsingCamera(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "TestScreenShots"))
        );

        Instance.Application.Browser.Manage().Window.Maximize();
    }
}
```

**Comment by robdmoore** [comment]
That should definitely work. Have you tried setting an explicit size rather than maximise to see if the same problem happens?

Also, what error does it fail with on the second test run?

## 

Rob Moore | Readify Principal Consultant, Technical Specialist (Microsoft Azure) | m +61 400 777 763 | e rob.moore@readify.net | w readify.net

**Comment by thnk2wn** [comment]
@robdmoore Not sure what changed but this seems to be working now. Thanks
