### ISSUE TITLE
How to do a scroll down (go to the top; go to the centre) on the page?

### ISSUE THREAD

**Issue by sirj77** [TestStack/TestStack.Seleno#213]
Hi,
just a simple question: How to do a scroll down to the bottom of the page properly? (this question is also for the go to the top/center of the page). My tests are needed to click on some element, but this element is located of the bottom of the page.

I tried to do like:
```c#
public void ScrollDownToTheBottomOfThePage()
{
 Browser.ExecuteJavaScript<??>("window.scrollTo(0, document.body.scrollHeight - 150)");
}
```
But I don't understand what I should put into ExecuteJavaScript<??> that my action would happen correctly.

**Comment by robdmoore** [comment]
Can you use Find.Element and then .Click?

Pretty sure web driver automatically scrolls when you do that...

**Comment by sirj77** [comment]
Yes, you are right, but what if I want to see the actions of clicking in a browser?

**Comment by robdmoore** [comment]
It should be visible to you while it happens?

**Comment by sirj77** [comment]
Just for the test purpose, it shouldn't be visible for me, actually :)

**Comment by robdmoore** [comment]
Right. So you want the Visible property of the IWebElement returned from Find.Element to be true?

**Comment by robdmoore** [comment]
Try this (without the click and changed for C#): http://stackoverflow.com/a/12042268

**Comment by sirj77** [comment]
**robdmoore**, thank you

**Comment by robdmoore** [comment]
Did that work for you? Feel free to post the final C# code so other people that find this know how to do it

**Comment by sirj77** [comment]
Well, I just wanted to observe the scroll down action in Browser while the tests are running. I've tried that piece of code that you sent me, but it didn't work, got some error, I tried it in a bit simple way (without scrolling to the particular element on the page, just scrolled down to the bottom of the page) and it works for me:
```c#
        public void ScrollDownToTheBottomOfThePage()
        {
            var js = String.Format("window.scrollTo(0, document.body.scrollHeight - 150)");
            Execute.Script(js);
        }
```
