### ISSUE TITLE
Not able to find an element using indexes and css selector if there is more than one identical element on the page

### ISSUE THREAD

**Issue by sirj77** [TestStack/TestStack.Seleno#214]
Hi,
I think, it is possible to find an element by index with css selector (in case if I'm having more than one element with the same name of selector expression), but  I'm getting an error even without running the tests.
Piece of code:
```C#
        public void Test()
        {
            Find.Elements(By.CssSelector(cssSelector))[1];
        }
```
So, on the test page I have 5 elements with the same selector - cssSelector, but I want to find the second one and do some actions with it or make an assertion. And the visual studio says me that there is an error (it underlines in read the "[1])": "Cannot apply indexing to an expression of type System.Collections.Generic.IEnumerable<OpenQA.Selenium.IWebElement".

What I should change to have this piece of code correct, without errors?

**Comment by robdmoore** [comment]
Try .ElementAt(1) rather than [1]

**Comment by sirj77** [comment]
**robdmoore**, thanks a lot, it works:
```c#
        public bool Test()
        {
            get { return Find.Elements(By.CssSelector(cssSelector)).ElementAt(1).Selected; }
        }
```
