### ISSUE TITLE
SelenoHost Instrance.Run  HTTPS

### ISSUE THREAD

**Issue by BetterOffWith28** [TestStack/TestStack.Seleno#215]
I'm new to Seleno.   Is there a way to set   Instance.Run("PeachCourt", 44300);
To  use "https",   say ->  https://locahost:44300     ??

**Comment by robdmoore** [comment]
You need to configure the IIS Express instance to run with HTTPS configured.

I suspect you can use a similar approach to the one documented here: https://github.com/TestStack/TestStack.Seleno/issues/90#issuecomment-129653907

Let me know how you go.

**Comment by BetterOffWith28** [comment]
Worked like a charm. Thanks robmoore.

**Comment by robdmoore** [comment]
No worries

Do you mind posting the code so someone else can do the same in the future?
