### ISSUE TITLE
How we can use indexes for the return Navigate.To<Page>(By));

### ISSUE THREAD

**Issue by sirj77** [TestStack/TestStack.Seleno#219]
Hi,

I've bumped into some problems that I cannot solve by myself.
Is there a way how I can use this expression:
```c#
return Find.Elements(By.CssSelector(SomeSelector)).ElementAt(0).Click();
```
for my interaction method throughout the pages:
```c#
        public GeneraPage GoToSomePage(string testLink)
        {
            return Navigate.To<GeneraPage >(By.CssSelector(SelectorCss + testLink+ "']"));
        }
```
I mean that I need to chose an element by index (because there are two or more elements on the page and I don't have a unique one) and go to an appropriate page. I know that there is no possibility to write like that:
 ```c#
        public GeneralPage GoToSomePage(string testLink)
        {
            return Navigate.To<GeneraPage >(By.CssSelector(SelectorCss + testLink+ "']")).ElementAt(0);
        }
```

How to rewrite this method properly?
Thanks a lot for suggestions!

**Comment by robdmoore** [comment]
Can you append `:nth-child(0)` to the css selector?

**Comment by sirj77** [comment]
Yes, you are right, it is one way how to do it, thanks. Actually, I managed to find a unique selector for my element.

But anyway, I guess, there is not possibility to rewrite method "GoToSomePage" using .ElementAt(0) in that construction? (return Navigate.To<GeneraPage >(By.CssSelector(SelectorCss + testLink+ "']")).ElementAt(0);)

**Comment by robdmoore** [comment]
Yeah - I don't think so. You need to pass a By expression to NAvigate.To that will return a single item.
