### ISSUE TITLE
What's the syntax for Find.Element(By.jQuery(...

### ISSUE THREAD

**Issue by RalphLavelle** [TestStack/TestStack.Seleno#223]
return Find.Element(By.jQuery("(\''span[data-meaning=in]:contains('en'), span[data-parts=Number]:contains('2015')'').parent()\"));

I'm getting a javascript error here, but I'm not sure what exact form my jQuery should take - I've tried putting in the "$' and leaving it out. Haven't a clue!

**Comment by robdmoore** [comment]
Does it work with: return Find.Element(By.jQuery("span[data-meaning=in]:contains('en'), span[data-parts=Number]:contains('2015')")).FindElement(By.XPath(".."));

**Comment by RalphLavelle** [comment]
Yes, thanks. So I have to switch to XPath? There's no way you know of to stay within jQuery to get a parent element like that? At least I can see the syntax of the jQuery I need to use now, ta.

**Comment by robdmoore** [comment]
I though there would have been, but I looked through the selectors doco page and nothing jumped out at me. I could have missed it though...
