### ISSUE TITLE
(Help) How to handle the same tests, but for different locales

### ISSUE THREAD

**Issue by sirj77** [TestStack/TestStack.Seleno#224]
Hi,

Is there a possibility to run all the automated test cases, but on different locales (countries)?
So, for instance, I have 50 tests that are run on one country (on one concrete url, that are specified in Host class):
```c#
    public static class Host
    {
        public static readonly SelenoHost Instance = new SelenoHost();

        static Host()
        {
            Instance.Run(configure => configure
                .WithWebServer(new InternetWebServer("http://my_site.com")));

            Instance.Application.Browser.Manage().Window.Maximize();
        }
    }
```

But there is a need to run these tests, but for the others countries, let's say for:
*.com.de
*.co.uk
*.es
*.dk
... and so on

Thank you for your help!

**Comment by robdmoore** [comment]
You could make hte URL a configuration variable (e.g. environment variable or app.config) and then re-run the whole test suite, but with the variable set differently each time?

**Comment by sirj77** [comment]
Thanks. I will try.
