### ISSUE TITLE
TableReader GetRowAt extremely slow performance

### ISSUE THREAD

**Issue by jacku-abide** [TestStack/TestStack.Seleno#225]
I using `TableFor<SimpleModel>("myId")` in one of my page models and I am noticing extremely slow performance when I try to use the indexer (`GetRowAt`). It may be due to the initial call to DisplayedProperties lazy load, I am not sure.

It takes about 12 seconds on my simple table with 1 row and ~10 columns. Only one cell/header has the `data-property-name` attribute populated (as we are using a custom grid renderer), the other cells have the `data-property-name` but *no value assigned* (e.g. `<td data-property-name>`. Perhaps this is causing the problem?

I have tried both PhantomJs and Chrome drivers. Both the same performance.

Any ideas?

**Comment by jacku-abide** [comment]
On inspection of `TableReader.cs` it does appear the use of `IEnumerable` may be a problem. Every time a row is accessed it will re-execute all of the code (such as `GetColumnNames`) because none of the enumerables are materializated into array, lists etc.

Is it a safe assumption that TableReader does not need to deal with dynamically changing columns when reading from a table? If so then things such as column names can be 'cached' simply by materilizing those enumerables.

**Comment by robdmoore** [comment]
Hmm, great question.

So we have an acceptance test that uses that functionality, I don't remember it running particularly slowly though. Can you run it and see if you get a similar result with that table?

Either way, one option could be to cache it, but a problem with that may be when you update the table with javascript. I say that without looking at the code though to see the ins and outs of it since I'm on the go.

Thoughts?

**Comment by jacku-abide** [comment]
Yes the table is likely to be updated by javascript, but I would be very surprised if the columns did. I think it would be fair to restrict the TableReader to expect a constant schema, or at least have one specialisation of  TableReader that did.

I am currently testing my own copy & paste version of TableReader to see if I can fix it. Will let you know.

**Comment by robdmoore** [comment]
Nice!

Good thinking. Feel free to send a PR if it works.

Thanks
