### ISSUE TITLE
Running tests with MSTest

### ISSUE THREAD

**Issue by crazybg321** [TestStack/TestStack.Seleno#242]
Hi,

I am trying to run my tests by using MSTest's command line interface. The weird thing is that I get an exception that chromedriver.exe cannot be found, while the file is in the folder. I also trying embedding the chromedriver.exe in the DLL containing my tests, the result was the same.

Do you have any suggestions how to fix this?

Thanks in advance!

**Comment by crazybg321** [comment]
Ok I found out that MSTest did not copy the chromedriver.exe to the Out folder. The fix was to use DeploymentItem on the method to force MSTest to copy it. (quite annoying though)

**Comment by robdmoore** [comment]
Can you please post more detail about the fix so anyone else with the same problem can solve it?

Thanks

--

**Comment by crazybg321** [comment]
The problem was that MSTest copies the files from the directory of the DLL containing the tests to a Out directory and runs the tests from there and by default it does not include the chromedriver.exe in that folder (don't know why). So the fix was adding the DeploymentItem("chromedriver.exe") attribute on the methods. 

With some further investigation I came to the conclusion that it is better to create a base test class that has that attribute and a page object field and all my test classes are extending it (meaning all of them require the chromedriver.exe).
