### ISSUE TITLE
Seleno: Debug automated UI tests

### ISSUE THREAD

**Issue by wijdenchebbi** [TestStack/TestStack.Seleno#245]
Hi,

How can i debug the automated UI tests using Seleno for an ASP.net MVC C# project.

**Comment by robdmoore** [comment]
Have you tried attaching to the iisexpress.exe that is spawned?

**Comment by wijdenchebbi** [comment]
Hi,
I didn't use this idea, can you explain me more.

**Comment by mwhelan** [comment]
I have some info [here](http://www.michael-whelan.net/testing-mvc-application-with-iis-express-webdriver/) in the section "Debugging the IIS Process." I hope it helps.
