### ISSUE TITLE
Access webdriver object in Seleno

### ISSUE THREAD

**Issue by justinhomes** [TestStack/TestStack.Seleno#248]
I am using Seleno for UI testing. Under the hood, it uses Selenium: https://github.com/TestStack/TestStack.Seleno

I need to interact with a download pop-up for Firefox.
A previous question's answer uses Selenium's webdriver:
Access to file download dialog in Firefox

How can I apply this solution in Seleno?

**Comment by robdmoore** [comment]
Yep. Access the Browser property from your page object and you are using selenium web driver.

**Comment by edwardrbaker** [comment]
Is it possible to get more detail around this? This is the only remotely helpful answer on the entire internet, and it's not very clear.
