### ISSUE TITLE
Telerik Report

### ISSUE THREAD

**Issue by wijdench** [TestStack/TestStack.Seleno#251]
Hi,

Can I get the text of a Telerik report generated in a link by selenuim webdriver  c#?
I just want to verify in Assertion that the report contains a string, 
Thanks.

**Comment by robdmoore** [comment]
You can grab the HTML source via the Browser property on the page object or you can search for an element on the page by text too. Does that meet your needs?

**Comment by wijdench** [comment]
I used `Find.Element(By.ClassName("s44")).Text;` but it return always null,

I tried to get all the document text by `js.ExecuteScript("return document.body.innerText;")` or `Find.Element(By.TagName("body")).Text` but it return just the page head that contains the menu and not the body .

I tried also this code `BrowserHost.Instance.Application.Browser.PageSource` to get the page source and it returns the body without the main part wich is the report document.

I dont know how to get into the report information.

**Comment by robdmoore** [comment]
Is the report within an iframe?

**Comment by wijdench** [comment]
Yes it is.

**Comment by robdmoore** [comment]
In that case you'll need to target your selectors to that frame.

Check this out: http://stackoverflow.com/questions/9607964/selenium-unable-to-access-iframe-and-data-inside-it

**Comment by wijdench** [comment]
Thanks for your response. It helps me a lot.

**Comment by robdmoore** [comment]
No worries :)
